Incs 5657 create generic react component for app configuration for starting screen
atlassian/atlassian-connect-example-app-node pull request #52
Opened 2024-01-18 22:18 UTC by lcaglar

Adding a generic landing page react component with reference to these design docs: https://www.figma.com/file/9PLctPRw78hehDvxB86vqC/Better-Configs?type=design&node-id=1-2&mode=design&t=B2KweNF920llL73a-0

Page follows the GH4J structure: 
- Explain what needs to be configured
- Explain what permissions are needed
- Links to guides/helpers

<img width="1367" alt="Screenshot 2024-01-19 at 9 09 18 am" src="https://github.com/atlassian/atlassian-connect-example-app-node/assets/156166275/22249459-4f7c-433d-93ff-43f853b42889">
<img width="1366" alt="Screenshot 2024-01-19 at 9 11 10 am" src="https://github.com/atlassian/atlassian-connect-example-app-node/assets/156166275/8d226d3b-afd3-40e6-9f27-e0c2ca71eb92">

2024-01-18 23:40 UTC, ttayeb-atlassian commented on spa/package.json
> +    "axios": "^1.6.5",
I dont think we're using axios in the app, can you please check if these packages are used in the spa package and remove them from dependancies if they arent 🙏

2024-01-18 23:41 UTC, ttayeb-atlassian commented on spa/public/logo192.png
can we remove these logos that are unused 🙏

2024-01-18 23:48 UTC, ttayeb-atlassian commented on spa/public/favicon.ico
do we need to set this favicon to something? i think we'll need to set it to whatever the github for jira apps favicon is - can you check with sarah?

2024-01-18 23:50 UTC, ttayeb-atlassian commented on spa/src/App.test.tsx
we should update this test to test your changes or remove it for now if we are adding tests later

2024-01-19 00:03 UTC, ttayeb-atlassian commented on spa/src/index.css
we should remove this

2024-01-19 00:04 UTC, krazziekay requested changes

2024-01-19 00:04 UTC, krazziekay commented on spa/src/index.tsx
> +reportWebVitals();
Please remove this too, since we're not using this.

2024-01-19 00:04 UTC, krazziekay commented on spa/src/reportWebVitals.ts
Don't think we'll be using this too, please remove this as well.

2024-01-19 00:04 UTC, krazziekay commented on yarn.lock
> +  resolved "https://packages.atlassian.com/api/npm/npm-remote/@atlaskit/analytics-next-stable-react-context/-/analytics-next-stable-react-context-1.0.1.tgz#93c4c7a1a35f4ab606d727af443f49f0842fd96f"
`packages.atlassian.com` can't be accessed by non-Atlassian devs. Will need to change the registry to `registry.npmjs.org`.

2024-01-19 00:04 UTC, krazziekay commented on spa/src/rest-interfaces/index.ts
These types are all specific to Github and I don't think we need these types for this case.

2024-01-19 00:45 UTC, ttayeb-atlassian commented on spa/src/pages/start-connection/ExampleComponent.tsx
> +		<>
i think the this file needs to be formatting, the indentation is off

2024-01-19 00:46 UTC, ttayeb-atlassian commented on spa/src/rest-interfaces/index.ts
we should remove this if unused

2024-01-19 00:48 UTC, ttayeb-atlassian commented on src/spa-proxy.ts
> +//import { isNodeDev } from "./utils/is-node-env";
we should remove this comment

2024-01-19 00:52 UTC, ttayeb-atlassian commented on spa/src/common/Wrapper.tsx
> +export const Wrapper = (attr: {
this looks like a wrapper for the page components? if it is can we rename this to PageWrapper

2024-01-19 00:52 UTC, ttayeb-atlassian commented on spa/src/common/Wrapper.tsx
> +					//onClick={navigateToHomePage}
should this be commented out?

2024-01-20 22:27 UTC, lcaglar commented on spa/package.json
> +    "axios": "^1.6.5",
Axios isn't used, I've removed it!

2024-01-20 22:31 UTC, lcaglar commented on spa/public/favicon.ico
The GH4J app doesn't seem to set the favicon to anything but yeah I'll ask Sarah to be sure

2024-01-20 22:32 UTC, lcaglar commented on spa/public/logo192.png
Done!

2024-01-20 22:32 UTC, lcaglar commented on spa/src/App.test.tsx
I've removed this file for now

2024-01-23 06:22 UTC, krazziekay reviewed
Minor comments

2024-01-23 06:22 UTC, krazziekay commented on spa/README.md
> +3.run ngrock:
Typo `ngrok`
And please do not share your own domain in such public doc.

2024-01-23 06:22 UTC, krazziekay commented on spa/README.md
While this makes sense to us, I'd still suggest to run this text by your team's content designer, cause this is where every 3P dev is gonna land at first.

2024-01-23 06:22 UTC, krazziekay commented on spa/package.json
> +  "name": "my-app",
\nit Should come up with a better name than `my-app`.

2024-01-23 06:22 UTC, krazziekay commented on spa/src/components/ExampleComponent/index.tsx
> +		<>
\nit Don't need these React Fragments.

2024-01-24 05:30 UTC, lcaglar commented on spa/README.md
I've added some more info to it while I wait to hear back from the designer!

2024-01-29 00:30 UTC, krazziekay approved these changes
Good work 👍

2024-01-29 00:31 UTC, krazziekay commented on spa/README.md
If it takes too long, then please do that in a separate PR. The rest of the stuff looks good.

2024-01-29 00:37 UTC, lcaglar commented on spa/README.md
Haven't heard back so I'll just do that, thanks

2024-01-29 03:55 UTC, krazziekay approved these changes

2024-01-29 04:00 UTC, merged